export const data = [
  {
    "id": 100,
    "name": "boAt Type C A325 Tangle-free, Sturdy Type C Cable with 3A Rapid Charging & 480mbps Data Transmission(Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71eVAHH3tsL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/boAt-A325-Tangle-Free-Charging-Transmission/dp/B08WRBG3XW/ref=sr_1_4?qid=1679128123&s=electronics&sr=1-4",
    "ratings": 4.1,
    "no_of_ratings": "14,024",
    "discount_price": "₹199",
    "actual_price": "₹499"
  },
  {
    "id": 1,
    "name": "Echo Dot (3rd Gen) - Alexa smart speaker with loud 360 degree sound & Bluetooth",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61EXU8BuGZL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Echo-Dot-3rd-Gen/dp/B07PFFMP9P/ref=sr_1_5?qid=1679128123&s=electronics&sr=1-5",
    "ratings": 4.4,
    "no_of_ratings": "98,293",
    "discount_price": "₹2,499",
    "actual_price": "₹4,499"
  },
  {
    "id": 2,
    "name": "Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/51Sk5hmB7nL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Portronics-Konnect-POR-1080-Charging-Function/dp/B08CF3B7N1/ref=sr_1_6?qid=1679128123&s=electronics&sr=1-6",
    "ratings": 4.2,
    "no_of_ratings": "17,708",
    "discount_price": "₹149",
    "actual_price": "₹399"
  },
  {
    "id": 3,
    "name": "Portronics Konnect L POR-1081 Fast Charging 3A Type-C Cable 1.2Meter with Charge & Sync Function for All Type-C Devices (G...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/51CvP9P2efL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Portronics-POR-1081-Charging-1-2Meter-Function/dp/B08CF3D7QR/ref=sr_1_7?qid=1679128123&s=electronics&sr=1-7",
    "ratings": 4.3,
    "no_of_ratings": "14,136",
    "discount_price": "₹129",
    "actual_price": "₹339"
  },
  {
    "id": 4,
    "name": "Duracell USB Type C, 3A Braided Sync & Fast Charging Cable, 3.9 Ft (1.2M), QC 2.0/3.0 Ultra Fast Charging, Compatible with...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71sMR4yd6UL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/DURACELL-Type-C-braided-Charge-Cable/dp/B09C6JXV8Y/ref=sr_1_8?qid=1679128123&s=electronics&sr=1-8",
    "ratings": 4.3,
    "no_of_ratings": "2,215",
    "discount_price": "₹368",
    "actual_price": "₹699"
  },
  {
    "id": 5,
    "name": "Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devi...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61ZeHF2Cf4L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Ambrane-Unbreakable-Charging-Braided-Cable/dp/B098NS6PVG/ref=sr_1_9?qid=1679128123&s=electronics&sr=1-9",
    "ratings": 4,
    "no_of_ratings": "45,983",
    "discount_price": "₹199",
    "actual_price": "₹299"
  },
  {
    "id": 6,
    "name": "boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71ctu8Z759L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/boAt-Micro-USB-Tangle-Free-Transmission/dp/B08WRWPM22/ref=sr_1_10?qid=1679128123&s=electronics&sr=1-10",
    "ratings": 4,
    "no_of_ratings": "15,967",
    "discount_price": "₹139",
    "actual_price": "₹499"
  },
  {
    "id": 7,
    "name": "Mi Type C 3Amp 100cm Fast Charge Cable Black|USB to Type C|Supports Upto 22.5W Fast Charging|Suitable for All Smartphones,...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71xuP3mbiRL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/MI-MTCY001IN-USB-Type-C-Cable/dp/B08DDRGWTJ/ref=sr_1_11?qid=1679128123&s=electronics&sr=1-11",
    "ratings": 4.3,
    "no_of_ratings": "31,112",
    "discount_price": "₹229",
    "actual_price": "₹299"
  },
  {
    "id": 8,
    "name": "boAt Rugged v3 Extra Tough Unbreakable Braided Micro USB Cable 1.5 Meter (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61b91WUDxmL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Rugged-Extra-Tough-Unbreakable-Braided/dp/B0789LZTCJ/ref=sr_1_12?qid=1679128123&s=electronics&sr=1-12",
    "ratings": 4.2,
    "no_of_ratings": "96,230",
    "discount_price": "₹299",
    "actual_price": "₹799"
  },
  {
    "id": 9,
    "name": "Samsung 80 cm (32 Inches) Wondertainment Series HD Ready LED Smart TV UA32T4340BKXXL (Glossy Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71a4ZQNqTiL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Samsung-Inches-Wondertainment-UA32T4340BKXXL-Glossy/dp/B09F6S8BT6/ref=sr_1_16?qid=1679128123&s=electronics&sr=1-16",
    "ratings": 4.2,
    "no_of_ratings": "8,877",
    "discount_price": "₹12,990",
    "actual_price": "₹22,900"
  },
  {
    "id": 10,
    "name": "Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/31IvNJZnmdL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Sounce-iPhone-Charging-Compatible-Devices/dp/B096MSW6CT/ref=sr_1_17?qid=1679128123&s=electronics&sr=1-17",
    "ratings": 3.9,
    "no_of_ratings": "7,408",
    "discount_price": "₹199",
    "actual_price": "₹999"
  },
  {
    "id": 11,
    "name": "Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iP...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71ojkmsYe8L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Wayona-Braided-WN3LG1-Syncing-Charging/dp/B07JW9H4J1/ref=sr_1_18?qid=1679128123&s=electronics&sr=1-18",
    "ratings": 4.2,
    "no_of_ratings": "25,351",
    "discount_price": "₹379",
    "actual_price": "₹1,099"
  },
  {
    "id": 12,
    "name": "pTron Solero MB301 3A Micro USB Data & Charging Cable, Made in India, 480Mbps Data Sync, Strong & Durable 1.5-Meter Nylon ...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/51mW4YZ7wXL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Solero-MB301-Charging-480Mbps-1-5-Meter/dp/B08Y1SJVV5/ref=sr_1_20?qid=1679128123&s=electronics&sr=1-20",
    "ratings": 3.9,
    "no_of_ratings": "26,310",
    "discount_price": "₹99",
    "actual_price": "₹666.66"
  },
  {
    "id": 13,
    "name": "Redmi 80 cm (32 inches) Android 11 Series HD Ready Smart LED TV | L32M6-RA/L32M7-RA (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71L-lTQnJiL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Redmi-inches-Ready-L32M6-RA-Android/dp/B09F9YQQ7B/ref=sr_1_21?qid=1679128123&s=electronics&sr=1-21",
    "ratings": 4.2,
    "no_of_ratings": "47,642",
    "discount_price": "₹13,999",
    "actual_price": "₹24,999"
  },
  {
    "id": 14,
    "name": "OnePlus 138 cm (55 inches) Y Series 4K Ultra HD Smart Android LED TV 55Y1S Pro (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/81Itairz1YL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/OnePlus-55-inches-Android-Pro/dp/B0BLVQBPCC/ref=sr_1_22?qid=1679128123&s=electronics&sr=1-22",
    "ratings": 4.2,
    "no_of_ratings": "8,290",
    "discount_price": "₹38,999",
    "actual_price": "₹49,999"
  },
  {
    "id": 15,
    "name": "PTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync, Strong and Durable 1.5-Meter ...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/51MIEYMrK-L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Solero-TB301-Charging-480Mbps-1-5-Meter/dp/B08Y1TFSP6/ref=sr_1_23?qid=1679128123&s=electronics&sr=1-23",
    "ratings": 3.9,
    "no_of_ratings": "26,310",
    "discount_price": "₹149",
    "actual_price": "₹1,000"
  },
  {
    "id": 16,
    "name": "TP-Link USB WiFi Adapter for PC(TL-WN725N), N150 Wireless Network Adapter for Desktop - Nano Size WiFi Dongle Compatible w...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61e61vCPY6L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/TP-Link-TL-WN725N-150Mbps-Wireless-Adapter/dp/B008IFXQFU/ref=sr_1_24?qid=1679128123&s=electronics&sr=1-24",
    "ratings": 4.2,
    "no_of_ratings": "183,124",
    "discount_price": "₹499",
    "actual_price": "₹999"
  },
  {
    "id": 17,
    "name": "tizum HDMI to VGA Adapter/ Connector/ Converter Cable 1080P (Male to Female) for Media Players, Xbox, Projector, Computer,...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61F4szMc-gL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Adapter-Projector-Computer-Laptop-Projectors/dp/B085194JFL/ref=sr_1_25?qid=1679128123&s=electronics&sr=1-25",
    "ratings": 3.7,
    "no_of_ratings": "11,431",
    "discount_price": "₹259",
    "actual_price": "₹499"
  },
  {
    "id": 18,
    "name": "Ambrane 60W / 3A Type C Fast Charging Unbreakable 1.5m L Shaped Braided Cable, PD Technology, 480Mbps Data Transfer for Sm...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61K4s3RQTrL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Ambrane-Charging-Unbreakable-Braided-Connector/dp/B09CMM3VGK/ref=sr_1_26?qid=1679128123&s=electronics&sr=1-26",
    "ratings": 4,
    "no_of_ratings": "2,262",
    "discount_price": "₹199",
    "actual_price": "₹499"
  },
  {
    "id": 19,
    "name": "OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71d5fMDvq9L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/OnePlus-inches-Ready-Android-32Y1/dp/B08B42LWKN/ref=sr_1_27?qid=1679128123&s=electronics&sr=1-27",
    "ratings": 4.2,
    "no_of_ratings": "36,800",
    "discount_price": "₹14,999",
    "actual_price": "₹19,999"
  },
  {
    "id": 20,
    "name": "Acer 80 cm (32 inches) I Series HD Ready Android Smart LED TV AR32AR2841HDFL (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/712am1RDNiL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Acer-inches-Ready-Android-AR32AR2841HDFL/dp/B0B1YVCJ2Y/ref=sr_1_28?qid=1679128123&s=electronics&sr=1-28",
    "ratings": 4.4,
    "no_of_ratings": "7,943",
    "discount_price": "₹10,999",
    "actual_price": "₹19,990"
  },
  {
    "id": 21,
    "name": "Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C to Type C Cable for Smartphones, Tablets, Laptops & Other T...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61oLp+pYPxL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Ambrane-Unbreakable-Charging-Braided-Cable/dp/B082LSVT4B/ref=sr_1_29?qid=1679128123&s=electronics&sr=1-29",
    "ratings": 4,
    "no_of_ratings": "45,983",
    "discount_price": "₹199",
    "actual_price": "₹299"
  },
  {
    "id": 22,
    "name": "Redmi 108 cm (43 inches) Android 11 Series Full HD Smart LED TV L43M6-RA/L43M7-RA (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71g3OF4CL9L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Redmi-inches-Smart-L43M6-RA-Android/dp/B09G73T643/ref=sr_1_30?qid=1679128123&s=electronics&sr=1-30",
    "ratings": 4.2,
    "no_of_ratings": "47,642",
    "discount_price": "₹21,999",
    "actual_price": "₹34,999"
  },
  {
    "id": 23,
    "name": "pTron Solero M241 2.4A Micro USB Data & Charging Cable, Made in India, 480Mbps Data Sync, Durable 1-Meter Long USB Cable f...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/51JVvqm1mAL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Solero-M241-Charging-480Mbps-Durable/dp/B08Y5Q1W3Y/ref=sr_1_28?qid=1679128124&s=electronics&sr=1-28",
    "ratings": 3.9,
    "no_of_ratings": "26,310",
    "discount_price": "₹89",
    "actual_price": "₹800"
  },
  {
    "id": 24,
    "name": "ZEBRONICS ZEB-USB150WF1 WiFi USB Mini Adapter Supports 150 Mbps Wireless Data, Comes with Advanced Security WPA/WPA2 encry...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61UC24Xk8BS._AC_UL320_.jpg",
    "link": "https://www.amazon.in/ZEBRONICS-ZEB-USB150WF1-Supports-encryption-Standards/dp/B093QCY6YJ/ref=sr_1_29?qid=1679128124&s=electronics&sr=1-29",
    "ratings": 3.7,
    "no_of_ratings": "2,317",
    "discount_price": "₹249",
    "actual_price": "₹499"
  },
  {
    "id": 25,
    "name": "VW 80 cm (32 inches) Frameless Series HD Ready Android Smart LED TV VW32S (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/81oHGrH1PwL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Visio-World-inches-VW32S-Ready/dp/B07MNNH484/ref=sr_1_30?qid=1679128124&s=electronics&sr=1-30",
    "ratings": 4,
    "no_of_ratings": "7,163",
    "discount_price": "₹7,999",
    "actual_price": "₹16,999"
  },
  {
    "id": 26,
    "name": "MI Type B/Micro USB 120cm fast Charging cable|480mbps support|Suitable for all Smartphones,tablet and accessories with typ...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61Mx3gDrY7L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Mi-Original-Cable-120cm-Black/dp/B07H4X1SCK/ref=sr_1_31?qid=1679128124&s=electronics&sr=1-31",
    "ratings": 4.2,
    "no_of_ratings": "36,509",
    "discount_price": "₹229",
    "actual_price": "₹299"
  },
  {
    "id": 27,
    "name": "Samsung 108 cm (43 inches) Crystal 4K Neo Series Ultra HD Smart LED TV UA43AUE65AKXXL (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71B7sRIydwL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Samsung-inches-Crystal-Ultra-UA43AUE65AKXXL/dp/B0B15CPR37/ref=sr_1_32?qid=1679128124&s=electronics&sr=1-32",
    "ratings": 4.3,
    "no_of_ratings": "7,879",
    "discount_price": "₹29,990",
    "actual_price": "₹47,900"
  },
  {
    "id": 28,
    "name": "Ambrane Unbreakable 3 in 1 Fast Charging Braided Multipurpose Cable for Speaker with 2.1 A Speed - 1.25 meter, Black",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71DGHA8osEL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Ambrane-Unbreakable-Charging-Braided-Multipurpose/dp/B094JNXNPV/ref=sr_1_33?qid=1679128124&s=electronics&sr=1-33",
    "ratings": 4,
    "no_of_ratings": "3,042",
    "discount_price": "₹299",
    "actual_price": "₹399"
  },
  {
    "id": 29,
    "name": "Samsung 108 cm (43 inches) Crystal 4K Series Ultra HD Smart LED TV UA43AUE60AKLXL (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/71eUw15rVbL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/Samsung-inches-Crystal-Ultra-UA43AUE60AKLXL/dp/B092BJMT8Q/ref=sr_1_34?qid=1679128124&s=electronics&sr=1-34",
    "ratings": 4.3,
    "no_of_ratings": "7,879",
    "discount_price": "₹28,990",
    "actual_price": "₹52,900"
  },
  {
    "id": 30,
    "name": "Amazon Basics High-Speed HDMI Cable - 10 Feet (Latest Standard) - Supports Ethernet, 3D, 4K video,Black",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61GUctqz0-L._AC_UL320_.jpg",
    "link": "https://www.amazon.in/AmazonBasics-High-Speed-HDMI-Cable-Standard/dp/B014I8T0YQ/ref=sr_1_35?qid=1679128124&s=electronics&sr=1-35",
    "ratings": 4.4,
    "no_of_ratings": "437,652",
    "discount_price": "₹379",
    "actual_price": "₹995"
  },
  {
    "id": 31,
    "name": "Tizum High Speed HDMI Cable with Ethernet | Supports 3D 4K | for All HDMI Devices Laptop Computer Gaming Console TV Set To...",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/61CHKsZkKzL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/TIZUM-Slim-1-5m-HDMI-Cable/dp/B01M4GGIVU/ref=sr_1_36?qid=1679128124&s=electronics&sr=1-36",
    "ratings": 4.2,
    "no_of_ratings": "12,457",
    "discount_price": "₹199",
    "actual_price": "₹699"
  },
  {
    "id": 32,
    "name": "MI 80 cm (32 inches) 5A Series HD Ready Smart Android LED TV L32M7-5AIN (Black)",
    "main_category": "tv, audio & cameras",
    "sub_category": "Home Entertainment Systems",
    "image": "https://m.media-amazon.com/images/I/81tD7OZ0RXL._AC_UL320_.jpg",
    "link": "https://www.amazon.in/MI-inches-Ready-Android-L32M7-5AIN/dp/B0B6F7LX4C/ref=sr_1_19?qid=1679128123&s=electronics&sr=1-19",
    "ratings": 4.2,
    "no_of_ratings": "34,286",
    "discount_price": "₹13,999",
    "actual_price": "₹24,999"
  },
]